services:
  my-postgres:
    image: jderobot/robotics-database:latest
    container_name: universe_db
    env_file: .env 
    environment:
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./RoboticsInfrastructure/database/universes.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/exercises/db.sql:/docker-entrypoint-initdb.d/2.sql
      - ./database/django_auth.sql:/docker-entrypoint-initdb.d/3.sql
      - ./scripts:/scripts
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 1s
      retries: 20

  robotics-academy-webapp:
      image: jderobot/robotics-academy:test
      container_name: developer-webapp
      entrypoint: ./webapp_dev.sh
      env_file: .env 
      ports:
        - "${SERVER_PORT}:7164"
      volumes:
        - type: bind
          source: ./
          target: /RoboticsAcademy
        - type: bind
          source: "${INFRASTRUCTURE_ABSOLUTE_PATH}"
          target: /Infrastructure
        - /var/run/docker.sock:/var/run/docker.sock
      tty: true
      stdin_open: true
      environment:
        DOCKER_HOST: "unix:///var/run/docker.sock"
      depends_on:
        my-postgres:
          condition: service_healthy
        
