from dotenv import load_dotenv
import os

# Carrega as variáveis do .env
load_dotenv()

"""
Django settings for academy project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
print("BASE_DIR", BASE_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--(47x6f9ah3wi=x-wuryrzl^&$kr+di_j#1a@-#%!(k+i6fbcd')

# GET PRODUCTION on .env and
PRODUCTION = os.getenv('PRODUCTION', 'False').lower() in ('true', '1', 't')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not PRODUCTION 

ALLOWED_HOSTS = ['localhost', '127.0.0.1'] if PRODUCTION else ['*']
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CSRF_TRUSTED_ORIGINS = [
    "https://127.0.0.1:7164",
    "https://localhost:7164",
]

# Cookies seguros (só enviados via HTTPS)
SESSION_COOKIE_SECURE = PRODUCTION
CSRF_COOKIE_SECURE = PRODUCTION

# Impede que páginas sejam carregadas em iframes (proteção contra clickjacking)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Redireciona todo tráfego HTTP para HTTPS
SECURE_SSL_REDIRECT = PRODUCTION  # (funciona se o request tiver is_secure())

# Proteções adicionais
SECURE_BROWSER_XSS_FILTER = PRODUCTION
SECURE_CONTENT_TYPE_NOSNIFF = PRODUCTION

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

VERSION = '13082021'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'exercises',
    'webpack_loader',                                       # Integrate React webpack bundles with Django
    'rest_framework',                                       # Django Rest Framework
    'academy.academy_rest_api.apps.AcademyRestApiConfig',   # Academy rest api application
    'react_frontend.apps.ReactFrontendConfig',               # React frontend application
    'corsheaders',
    'django_celery_beat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'react_frontend'),
            os.path.join(BASE_DIR, 'exercises'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',
                'academy.context_processors.version',
            ],
        },
    },
]

WSGI_APPLICATION = 'academy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'), #my-postgres
        'PORT': os.getenv('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = 'staticfiles'

STATICFILES_DIRS = (
    # os.path.join(BASE_DIR, "static"),
    os.path.join(BASE_DIR, 'react_frontend/static'),    # React frontend statics
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Settings for django webpack loader
WEBPACK_LOADER = {
  'DEFAULT': {
    'BUNDLE_DIR_NAME': 'react_frontend/',
    'CACHE': not DEBUG,
    'STATS_FILE': os.path.join(BASE_DIR, 'react_frontend/webpack-stats.json'),
    'POLL_INTERVAL': 0.1,
    'IGNORE': [r'.+\.hot-update.js', r'.+\.map'],
  }
}


CORS_ORIGIN_ALLOW_ALL = True


CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

CORS_ALLOW_CREDENTIALS = True

#INDICATES IF THERE IS A NVIDIA'S GPU ON HOST MACHINE
#DEFAULT VALUE IS "0"
GPU_AVAILABLE = os.getenv("GPU_AVAILABLE", "0")

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Sao_Paulo'
CELERY_ENABLE_UTC = False

PROJECT_ABSOLUTE_PATH=os.getenv("PROJECT_ABSOLUTE_PATH","")
INFRASTRUCTURE_ABSOLUTE_PATH =os.getenv("INFRASTRUCTURE_ABSOLUTE_PATH","")

LOGIN_URL = '/login/'
SERVER_PORT = os.getenv("SERVER_PORT", "7164") 
IS_GUIDE_CONTAINER_SAME_MACHINE = os.getenv("IS_GUIDE_CONTAINER_SAME_MACHINE", "true")
EXERCISE_GUIDE_URL = os.getenv("EXERCISE_GUIDE_URL", "https://jderobot.github.io/RoboticsAcademy/exercises")

COMPOSE_PROJECT_NAME=os.getenv("COMPOSE_PROJECT_NAME", "cimatec-academy")

#In hours
USER_CONTAINER_EXPIRATION=int(os.getenv("USER_CONTAINER_EXPIRATION", default=8))

#In minutes
INACTIVE_TIMEOUT=int(os.getenv("INACTIVE_TIMEOUT", default=30))

# Session's duration in seconds
SESSION_COOKIE_AGE = int(os.getenv('USER_SESSION_EXPIRATION', default=7200)) 

# If True, session will be finished when broswer is totally closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Reload SESSION_COOKIE_AGE timeout when a request is made
SESSION_SAVE_EVERY_REQUEST = True

# Configuration to email responsible to send password recovery link
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.getenv('EMAIL_HOST','smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', default=587))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER','barretto.smtp@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'fiye titx nqrm qltq')
PASSWORD_RESET_TIMEOUT = int(os.getenv('PASSWORD_RESET_TIMEOUT', default=1800))
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "no-reply@seu-dominio.com"

