# Generated by Django 4.1.7 on 2025-08-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidePageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
                ("category_identify", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "db_table": "guide_page_categories",
            },
        ),
        migrations.CreateModel(
            name="NodeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, unique=True)),
            ],
            options={
                "db_table": "nodes_types",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="guide_page_category",
            field=models.OneToOneField(
                db_column="guide_page_categories_id",
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="exercises.guidepagecategory",
            ),
        ),
    ]
