# Generated by Django 4.1.7 on 2025-08-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_guidepagecategory_nodetype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universe",
            name="robot",
            field=models.ForeignKey(
                db_column="robot_id",
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="exercises.robot",
            ),
        ),
    ]
