# Generated by Django 4.1.7 on 2025-08-25 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_alter_universe_robot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="guide_page_category",
            field=models.ForeignKey(
                db_column="guide_page_categories_id",
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="exercises.guidepagecategory",
            ),
        ),
    ]
