# Generated by Django 4.1.7 on 2025-10-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0004_alter_exercise_guide_page_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="nodetype",
            name="description",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="nodetype",
            name="need_topic_name",
            field=models.BooleanField(default=False),
        ),
    ]
